
base_url = "http://localhost:9999/v1/"
case_ep = "case"
trader_ep = "trader"
limits_ep = "limits"
news_ep = "news"
assets_ep = "assets"
securities_ep = "securities"
tenders_ep = "tenders"
leases_ep = "leases"
his_ep = "/history"
order_book_ep = "/book"
tas_ep = "/tas"
orders_ep = "orders"
id_ep = "{id}"
bulk_cancel_ep = "commands/cancel"